# Generated by Django 5.0.3 on 2024-04-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devume", "0011_alter_apikey_key_alter_city_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(
                default="b319144df876403bbad04c7ce2f318e5",
                max_length=255,
                unique=True,
            ),
        ),
    ]
