# Generated by Django 5.0.3 on 2024-04-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devume', '0020_alter_apikey_key_alter_education_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default='58b4f36e06264fc8b6cb38e7a53a33c5', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
