# Generated by Django 5.0.3 on 2024-04-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devume', '0022_alter_apikey_key_alter_skill_id'),
        ('devume', '0022_profile_skills_alter_apikey_key_delete_profile_skill'),
    ]

    operations = [
    ]
