# Generated by Django 5.0.3 on 2024-04-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devume", "0024_alter_apikey_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(
                default="9e37bb65022a48bcab60a615b354eeee", max_length=255, unique=True
            ),
        ),
    ]
