# Generated by Django 5.0.3 on 2024-05-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devume", "0026_alter_apikey_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="state",
        ),
        migrations.AddField(
            model_name="profile",
            name="link_1",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="link_2",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="link_3",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(
                default="590bce31995d4b59b59b1770c18e3fac", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
