# Generated by Django 5.0.3 on 2024-05-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devume", "0027_remove_profile_city_remove_profile_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="job_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(
                default="82815efdb86b42fbbb68005ad57c859f", max_length=255, unique=True
            ),
        ),
    ]
