name: Documentation

on:
  pull_request:
    branches:
      - main

jobs:
  generate_documentation:
    name: Generate Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run DRF Spectacular
        run: |
          python manage.py spectacular --file schema.yml

      - name: Commit documentation changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout ${{ github.event.pull_request.head.ref }}
          git add schema.yml
          git commit -m "Generate documentation"
          git push origin ${{ github.event.pull_request.head.ref }}
